export const colourOptions = [
  { value: "Machine Learning", label: "Machine Learning" },
  { value: "Artificial Intelligence", label: "Artificial Intelligence" },
  { value: "Big Data", label: "Big Data" },
  { value: "Software Engineering", label: "Software Engineering" },
  { value: "Neural Networks", label: "Neural Networks" },
  { value: "Cloud Computing", label: "Cloud Computing" },
  { value: "Cyber Security", label: "Cyber Security" },
  { value: "Robotics", label: "Robotics" },
  { value: "Programming", label: "Programming" },
  { value: "IOT", label: "IOT" },
  { value: "Blockchain", label: "Blockchain" },
  { value: "Hyper Automation", label: "Hyper Automation" },
  { value: "Extended Reality", label: "Extended Reality" },
  { value: "Quantum Computing", label: "Quantum Computing" },
  { value: "Nanotechnology", label: "Nanotechnology" },
  { value: "Other", label: "Other" },
];